---
- name: install jenkins
  hosts: all
  become: yes
  tasks:
    - name: Download jenkins
      apt_key:
       url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present 

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
      key: 'http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      state: present

    - name: Install java
      apt:
      name: java-11-openjdk-devel
      state: present

    - name: Install jenkins
      apt:
      name: jenkins
      state: latest

    # - name: daemon-reload to pick up config changes
    #   ansible.builtin.systemd:
    #   daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
      name: jenkins
      state: started