---
- name: install jenkins
  hosts: all
  become: yes
  tasks:
    - name: Download jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present 
    - name: add repo 
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: package
      package:
        update_cache: yes

    - name: Install java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install jenkins
      apt:
        name: jenkins
        state: latest

    - name: Start_jenkins
      service:
        name: jenkins
        state: started
