---
- name: setup elasticsearch
  hosts: all
  become: yes
  tasks:
    - name: Add Elasticsearch apt key
      apt_key:
       url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
       state: present
    # - name: Install APT repository
    #   apt:
    #     name: apt-transport-https
    #     state: present

    - name: install elasticsearch repo
      apt_repository:
       repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main" 
       state: present

    - name: Install Elasticsearch
      apt:
        name: elasticsearch=7.17.0
        update_cache: yes

    - name: Updating the config file of elasticsearch
      lineinfile:
       destfile: /etc/elasticsearch/elasticsearch.yml
       regexp: 'network.host:'
       line: 'network.host: 0.0.0.0'

    - name: Updating the port in config file 
      lineinfile:
       destfile: /etc/elasticsearch/elasticsearch.yml
       regexp: 'http.port:'
       line: 'http.port: 9200'

    - name: Updating the config file to allow outside access
      lineinfile:
       destfile: /etc/elasticsearch/elasticsearch.yml
       regexp: 'cluster.initial_master_nodes:'
       line: 'cluster.initial_master_nodes: ["{{ ansible_default_ipv4.address }}"]'
    - name: Starting Elasticsearch
      service:
       name: elasticsearch
       state: started
    
